version: '3'
services:
  zeo:
    build:
      context: .
    image: imioweb
    volumes:
      - ./var/blobstorage:/home/imio/imio-website/var/blobstorage
      - ./var/filestorage:/home/imio/imio-website/var/filestorage
    command: zeoserver fg
    expose:
      - 8100
    healthcheck:
      # test: ["CMD-SHELL", "nc", "-z", "w5", "127.0.0.1", "8100", "||", "exit", "1"]
      test: ['CMD', 'nc', '-z', '-w5', '127.0.0.1', '8100']
  instance:
    image: imioweb
    expose:
      - 8080
    links:
      - zeo:db
    depends_on:
      - reverseproxy
    command: fg
    deploy:
      replicas: 2
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.instance.rule=Host(`portal.localhost`)'
      - 'traefik.http.routers.instance.entrypoints=web'
      - 'traefik.http.services.instance.loadbalancer.server.port=8080'
  reverseproxy:
    image: traefik:2.0
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--entryPoints.web.address=:80'
    ports:
      - '80:80' # The HTTP port
      - '8000:8080' # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
