version: '3'
services:
  zeo:
    build:
      context: .
    image: imioweb
    volumes:
      - ./var/blobstorage:/home/imio/imio-website/var/blobstorage
      - ./var/filestorage:/home/imio/imio-website/var/filestorage
    command: zeoserver fg
    expose:
      - 8100
    healthcheck:
      # test: ["CMD-SHELL", "nc", "-z", "w5", "127.0.0.1", "8100", "||", "exit", "1"]
      test: ["CMD", "nc", "-z", "-w5", "127.0.0.1", "8100"]
  instance:
    image: imioweb
    expose:
      - 8080
    links:
      - zeo:db
    depends_on:
      - reverseproxy
    command: fg
    deploy:
      replicas: 2
    labels:
        - "traefik.frontend.rule=Host:localhost; AddPrefix: /VirtualHostBase/http/localhost/plone/VirtualHostRoot"
  reverseproxy:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
      - "8000:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  proxy:
